### PR TITLE
Upgrade web3 to 1.0.0-beta.48

### LINKED ISSUE #135: Support web3@^1.0.0-beta.38
As of 1.0.0-beta.38, web3 ships directly with typescript typings (they seem to no longer be published through @types/web3 as of now). Ideally these typings would be used.

After this version of web3, typechain now throws a bunch of errors with the web3-1.0 target:

```
build/wrappers/A.d.ts:4:58 - error TS2307: Cannot find module 'web3/eth/contract'.

4 import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
                                                           ~~~~~~~~~~~~~~~~~~~

build/wrappers/A.d.ts:5:46 - error TS2307: Cannot find module 'web3/eth/types'.

5 import { TransactionObject, BlockType } from "web3/eth/types";
                                               ~~~~~~~~~~~~~~~~

build/wrappers/A.d.ts:6:10 - error TS2305: Module '"web3/types"' has no exported member 'Callback'.

6 import { Callback, EventLog } from "web3/types";
           ~~~~~~~~

build/wrappers/A.d.ts:6:20 - error TS2305: Module '"/web3/types"' has no exported member 'EventLog'.

6 import { Callback, EventLog } from "web3/types";
                     ~~~~~~~~

build/wrappers/A.d.ts:8:26 - error TS2307: Cannot find module 'web3/providers'.

8 import { Provider } from "web3/providers";
```

### PR DESCRIPTION
**Pull request by cryptokat**
fix #135

### CODE REVIEW

**Comment by eswarasai** [comment]
@cryptokat -- I think this PR is looking good to generate typings for `web3@1.0.0-beta` with default typings. But dropping the legacy support isn't really good idea at this stage as there might be lot of projects out there relying upon `web3@0.20.x`. I'm sure @krzkaczor will agree on this.

**Comment by cryptokat** [comment]
@eswarasai I decided to drop legacy support because of broken `test/package-test` that needs `web3@1.0.0-beta.48` to be working, otherwise the dependencies on the sub packages of web3 such as `web3-core` will cause compilation error.

**Comment by krzkaczor** [comment]
Dropping legacy support is a no-go. Personally, I feel like web3 0.20.x is way more stable. Please revert the removal and tmrw I will help you fixing those failing tests (sorry it's late at night here).

**Comment by cryptokat** [comment]
@eswarasai @krzkaczor I reverted the removal of legacy support and fixed the package-test by excluding it from tsc compilation https://github.com/ethereum-ts/TypeChain/pull/141/commits/ddc6ae0f61ce1563b2453934ff0dc1eb6b40fe26 . Please have a look if that's alright.

**Comment by cryptokat** [comment]
In case that you are not aware of the error I mentioned above, here's the error I was getting from package-test before excluding it from tsc compilation:
Selection_096

**Comment by krzkaczor** [comment]
@cryptokat thanks! Frankly, I can't reproduce these problems that you were encountering but I think ignoring package-test in global tsconfig.json file makes sense.

**Comment by krzkaczor** [comment]
btw. i think this is slightly related to: https://github.com/ethereum-ts/TypeChain/pull/129

**Comment by krzkaczor** [comment]
@cryptokat @eswarasai PR looks fine for me. Did anyone of you tested it locally in your projects? I can merge this and publish new version today.

**Comment by eswarasai** [comment]
@krzkaczor -- I haven't tested this locally but the changes are looking good to me. I think we're missing a use case here where people might be using `web3.js` and the types from `@types/web3` in their existing codebase and might not be easy for them to upgrade to the types within `web3.js`.

It might help devs to know what are the breaking changes within this release and what's not supported going forward in the `README.md`. Let me know if that makes sense. Thanks!

**Comment by krzkaczor** [comment]
@eswarasai yeah I imagine that people would use current ie. `0.3.11` version if they want to stick with older web3.js (without embedded types). 

Yes, I will for sure leave a note about it in the changelog once it's merged. Thanks for reminder 😆

**Comment by krzkaczor** [comment]
Thank you for contributing! @cryptokat  🎉 

Released as `typechain@0.3.12`

**Comment by bryanwho** [comment]
In my project the ```Transaction``` parameter taken by the ```send()``` is the wrong interface after updating and following this thread. It requires all values to be passed in as seen here:

Screen Shot 2019-04-01 at 6 32 06 PM

which leads to this error Im getting:

Screen Shot 2019-04-03 at 10 38 33 AM

I think it has something to do with the ```Transaction``` object ```web3-core``` is importing in the ```type.d.ts``` file. The value should be of type ```any```

Screen Shot 2019-04-03 at 11 04 42 AM

Is anyone else encountering this issue? Fore reference I am using the latest web3 and typechain

**Comment by krzkaczor** [comment]
Hey @bryanwho could you create small repo example? I will get this sorted out

**Comment by bryanwho** [comment]
@krzkaczor just sent you an invite to a skeleton repo

**Comment by bryanwho** [comment]
Hey @krzkaczor any follow up on this: https://github.com/bryanwho/TypeChainTesting

**Comment by jchen86** [comment]
@bryanwho @krzkaczor I'm having the same issue mentioned above with the latest web3 and typechain. Please see this repo

https://github.com/jchen86/typechain-web3-pr-114/blob/2debfa4278029f30923c5c047ae4fb6c06187a0e/test/simple-storage.test.ts#L6

Screenshot 2019-05-07 at 11 02 45

**Pull request merged**
