### PR TITLE
Ethers.js generation improvements

### PR DESCRIPTION
**Pull request by frostiq**

### CODE REVIEW

**Comment by krzkaczor** [comment]
@frostiq have you tried running ‘yarn test:fix’? It should run formatting in fix mode.

**Comment by frostiq** [comment]
Thanks, @krzkaczor, it helped! :)
Pls take a look at my pr

**Comment by frostiq** [comment]
Sure, no prob @krzkaczor 
I've added a test for transaction overrides

**Comment by krzkaczor** [comment]
Thanks for your contribution @frostiq! I am gonna release it in a sec.

**Comment by krzkaczor** [comment]
Released as: `typechain@0.3.11`

**Comment by frostiq** [comment]
Thanks, @krzkaczor!

**Pull request merged**
