### PR TITLE
[ethers-v5] Export contract types in index.ts

### PR DESCRIPTION
**Pull request by zemse**
#278

Before:
```
<Contract>.d.ts
<Contract>Factory.ts
```

Only Factory file was exported

After:
```
<Contract>.ts
<Contract>Factory.ts
```

Now both the ts files are exported from `index.ts`

I've tried this PR on my current project, and didn't get any breakings. Though it can be tried on multiple projects to be sure.

### CODE REVIEW

**Comment by zemse** [comment]
I was thinking why even we are having 2 files, when we can have just one?

```
<Contract>.ts // exports both Contract abstract class and ContractFactory class
```

**Comment by quezak** [comment]
1. One big question first: why did you mark the generated class as abstract? It's not abstract, since it's just a more strictly typed extension of the concrete `Contract` class exported from Ethers.

2. Re `.ts` files for contract classes: I'm for it, but maybe @krzkaczor will oppose since he initially created this generator with just the type declarations being generated :) One reason was to avoid adding runtime overhead, but IMO that's not a big issue. And having only type declarations actually prevented me a few times to do useful tricks with the generated classes, for example passing a contract subclass to a helper function, or using `contractInstance.constructor.name`. One potential problem here are the factories: because `connect` just returns `super.connect`, the resulting object will be a plain `Contract` instance -- but if we'd add concrete `.ts` files for contract classes, it should produce instances of that class, so the factories should probably be updated.

3. Re 2 separate files -- I think that's OK, it's a common convention that `Xyz` class is exported from `xyz.ts`. Another reason to not merge the 2 files is that the factory file can be long, since it contains the contract ABI JSON.

**Comment by zemse** [comment]
### Marking abstract

I thought it this way: If we see `Contract` from typescript's eyes (assuming a erc20 contract instance), then according to typescript there is no such `transfer` method (assuming the [wild card](https://github.com/ethers-io/ethers.js/blob/d817416bae2fbc7adb8391fd038613241b7ab8ba/packages/contracts/src.ts/index.ts#L572) is not there). But we know that infact a method exists there in javascript level, but whose implementation is not in the typescript. So typescript would allow two ways working with this abstract class:

1. Inherit it in other class and implement the methods in typescript level (which we dont do)
2. Have a function that returns an object that implements these methods in JS level and put return type of this abstract class. (this is what the contract factory is).

The second point might be my misconception, since type definitions (`.d.ts`) files are for this purpose. But I thought it could be fine to use abstract classes as a replacement for type definations.

### Re .ts files for contract classes

I tried a lot of ways to make everything export from `index.ts` in the past time when I was making the first PR. But all my attempts failed. I finally gave up with only exporting the factories. Now, this is the only way I have found yet that actually doesn't error when run in my project. Importing `d.ts` files in other files result in an error `module not found`.

> I'll try to run the updated code anyway tomorrow and see the results.

That'd be really great!

### Re 2 separate files 

Ok actually that's not a problem

**Comment by krzkaczor** [comment]
First of all thanks @zemse for working on this!

Can't we just keep changes in this PR minimal to fix #278 ? I always preferred for TypeChain to generate pure types as this simplifies things and has no runtime impact. Then we don't need to debate on use of `abstract` keyword either ;) 

To make it work you might need `export type`: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

**Comment by zemse** [comment]
Okay, thanks for giving the pointer for Type-Only Imports and Exports! By looking at the docs, I think this should solve the problem.

**Comment by zemse** [comment]
Hi @krzkaczor I think there is some problem in `ts-generater` when using type imports:

```ts
Error occured:  '=' expected. (8:15)
   6 |   import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";
   7 | 
>  8 |   import type { ContractName } from "./ContractName";
     |               ^
   9 | 
  10 |   export class ContractNameFactory extends ContractFactory {
  11 |     
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

This problem comes when generating typechain files in the project.

**Comment by krzkaczor** [comment]
@zemse yeah it seems like `ts-generator` needs to be updated and `prettier` version bumped. It will be a breaking change regarding formatting. Can you just commit all your work for this PR and I will take care of fixing this problem?

**Comment by zemse** [comment]
The changes are minimal, but I fear it might not work due to further some error, and might need to be tweaked

**Comment by krzkaczor** [comment]
Merged to tmp branch for now

**Pull request merged**
