### PR TITLE
Update ethers-v6 target to support `Result` methods

### LINKED ISSUE #817: ethers-v6: Please consider implementing `Result` methods like `toArray()` and `toObject()`
https://github.com/ethers-io/ethers.js/blob/main/src.ts/abi/coders/abstract-coder.ts#L138

https://github.com/ethers-io/ethers.js/blob/main/src.ts/abi/coders/abstract-coder.ts#L153

Both methods are invaluable to most common use-cases. Thank you.

### PR DESCRIPTION
**Pull request by shirotech**
fixes #817

### CODE REVIEW

**Comment by krzkaczor** [comment]
Thanks! Merged as : https://github.com/dethcrypto/TypeChain/pull/866

**Comment by krzkaczor** [comment]
Sorry, no this is not merged yet.

**Comment by shirotech** [comment]
@krzkaczor please let me know anything you need on this before it can be merged? Thank you.

**Comment by krzkaczor** [comment]
@shirotech can you rebase with current master and run `test:fix` and fix all the errors. Please follow contributing guide when in doubt.

**Comment by handanyolak** [comment]
Are there any updates here?

**Pull request closed without merging**
