### PR TITLE
Truffle v5 support

### PR DESCRIPTION
**Pull request by krzkaczor**
- [ ] rename and release old truffle package as `typechain-target-truffle-v4`
- [x] release `@typechain/truffle-v5`
- [ ] update examples repo for v5
- [ ] add readme links to examples
- [ ] add tests to v5

### CODE REVIEW

**Comment by PetarKirov** [comment]
Hi @krzkaczor, what is left to be done here? I tried locally the branch this PR is based on and it worked great :)

**Comment by krzkaczor** [comment]
@PetarKirov thanks for testing. It should work. The todo is in the PR description, mostly its "infra" stuff as I ran into problems with releasing new packages on NPM. 

Sorry for the drag, it should be released in the next upcoming days.

**Comment by PetarKirov** [comment]
No worries, thanks for working on this nice project!

**Comment by krzkaczor** [comment]
It's released as `@typechain/truffle-v5`. Make sure to update core package to load `@typechain` namespaced packages...

**Comment by TripleSpeeder** [comment]
I installed @typechain/truffle-v5, but I'm not sure how to update the core package to make use of the new target... Is this available on npm already?

**Comment by krzkaczor** [comment]
@TripleSpeeder sorry, this branch is a hot mess right now. 

Some pointers are here: https://github.com/ethereum-ts/truffle-typechain-example/pull/7

**Comment by krzkaczor** [comment]
This is being merged into https://github.com/ethereum-ts/TypeChain/pull/219

It will done really soon! (~1 week), I need to write some tests and add support for overloaded events/methods.

**Pull request closed without merging**
